{
 "title": "OpenVPN Metrics",
 "description": "Simple OpenVPN Metrics dashboard for Prometheus openvpn_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "query_result(openvpn_up)" } },
   {
    "name": "interval",
    "query": "5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Whether scraping OpenVPN's metrics was successful.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time since last status update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - openvpn_status_update_time_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total{instance=\"$instance\"}[1d]))"
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total{instance=\"$instance\"}[1d]))"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(openvpn_server_client_received_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[1d]))by(virtual_address))",
     "legendFormat": "{{ virtual_address }}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OpenVPN Exporter Status",
   "type": "graph",
   "description": "Whether scraping OpenVPN's metrics was successful.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openvpn_up{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (openvpn_server_connected_clients{instance=\"vpn\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes Sent [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(openvpn_server_client_sent_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes Received [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(openvpn_server_client_received_bytes_total{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Traffic",
   "type": "graph",
   "description": "Top 10 total traffic by users.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(openvpn_server_client_received_bytes_total{instance=\"$instance\",common_name!=\"UNDEF\"}[$interval])+increase(openvpn_server_client_sent_bytes_total{instance=\"$instance\",common_name!=\"UNDEF\"}[$interval]))by(virtual_address))",
     "legendFormat": "{{ virtual_address }}"
    }
   ]
  },
  {
   "title": "Top 5 Client Network Activity [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (virtual_address) (increase(openvpn_server_client_received_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])))",
     "legendFormat": "{{ virtual_address }} - RX"
    },
    {
     "expr": "topk(5, sum by (virtual_address) (increase(openvpn_server_client_sent_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])))",
     "legendFormat": "{{ virtual_address }} - TX"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(rate(openvpn_server_client_received_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval]), \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address))"
    },
    {
     "expr": "sum(label_replace(rate(openvpn_server_client_sent_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval]), \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    },
    {
     "expr": "sum(label_replace(increase(openvpn_server_client_sent_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval]), \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address) + sum(label_replace(increase(openvpn_server_client_received_bytes_total{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval]), \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    }
   ]
  }
 ]
}