{
 "title": "Processes metrics MOD",
 "description": "Process exporter dashboard",
 "tags": [ "process" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU / Absolute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) > 0) / on(instance) group_left sum (rate(node_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU / Proportional",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(groupname) (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]) > 0) / on(instance) group_left sum (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Proportional resident memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"proportionalResident\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Resident memory per process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"resident\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Processes number",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{instance=~\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{instance=~\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Voluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$instance\", ctxswitchtype=\"voluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Nonvoluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$instance\", ctxswitchtype=\"nonvoluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Major page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_major_page_faults_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Minor page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_minor_page_faults_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (avg by (groupname) (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$instance\"} > 0))",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}