---
- hosts: "{{selected_hosts}}"
  become: true
  roles:
    - { role: ansible-role-repo-epel, when: ansible_os_family == 'RedHat' }
  vars:
    selected_hosts: all
  tasks:
  - fail:
      msg: This is not Centos
    when: ansible_distribution != 'CentOS'
    
  - name: Import ELRepo key
    rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    
  - name: Install ELRepo
    yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present
    
  - name: Enable ELRepo Kernel
    command: yum-config-manager --enable elrepo-kernel
    
  - name: Install Kernel-LT
    package:
      name:
        - kernel-ml
        - kernel-ml-headers
        - kernel-ml-tools
        - kernel-ml-devel
        - yum-utils
      state: latest

  - name: Set new kernel as default
    command: grub2-set-default 0 && grub2-mkconfig -o /boot/grub2/grub.cfg

  - name: Remove Old kernels
    command: package-cleanup --oldkernels -y