---
- hosts: "{{selected_hosts}}"
  become: true
  roles:
    - { role: ansible-role-repo-epel, when: ansible_os_family == 'RedHat' }
  vars:
    kernel-version: lt
  tasks:
  - fail:
      msg: This is not Centos
    when: ansible_distribution != 'CentOS'

  - name: Import ELRepo key
    rpm_key:
      state: present
      key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

  - name: Install ELRepo
    yum:
      name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
      state: present

  - name: Enable ELRepo Kernel
    command: 'yum-config-manager --enable elrepo-kernel'

  - name: Remove old headers
    package:
      name:
        - kernel-headers
        - kernel-tools
        - kernel-tools-libs
        - kernel-devel
      state: absent

  - name: "Install Kernel-{{ kernel-version }}"
    package:
      name:
        - "kernel-{{ kernel-version }}"
        - "kernel-{{ kernel-version }}-headers"
        - "kernel-{{ kernel-version }}-tools"
        - "kernel-{{ kernel-version }}-devel"
        - yum-utils
      state: latest

  - name: Set new kernel as default
    command: 'grub2-set-default 0'

  - name: Apply new kernel
    command: grub2-mkconfig -o /boot/grub2/grub.cfg

  - name: Remove Old kernels
    command: 'package-cleanup --oldkernels -y'
