---
- hosts: "{{selected_hosts}}"
  become: true
  roles:
  - { role: jnv.debian-backports, when: ansible_os_family == 'Debian' }
  tasks:
  - name: 'Check if supported OS'
    fail:
      msg: "It's not Debian family OS"
    when: ansible_os_family != 'Debian'

  - name: Upgrade kernel
    apt:
      name: "linux-image-{{'amd64' if ansible_distribution == 'Debian' else 'virtual'}}"
      state: latest
      default_release: "{{ansible_distribution_release}}-backports"
