# syntax=source.ansible
# https://github.com/prometheus-community/ansible/tree/main/roles/prometheus
# https://prometheus-community.github.io/ansible/branch/main/prometheus_role.html#ansible-collections-prometheus-prometheus-prometheus-role
---
- hosts: "{{ selected_hosts }}"
  become: true
  roles:
    - prometheus.prometheus.prometheus
