# syntax=source.ansible
# https://github.com/patrickjahns/ansible-role-promtail
---
- hosts: "{{ selected_hosts }}"
  become: true
  roles:
    - { role: ansible-role-promtail, when: promtail_config_scrape_configs| length >0 }
