# https://github.com/geerlingguy/ansible-role-docker
- hosts: "{{ selected_hosts }}"
  become: true
  pre_tasks:
  - name: Ensure Python setuptools present
    package:
      name: "{{ 'python3-setuptools' if ansible_python_version is version('3', '>=') else 'python-setuptools' }}"
      state: present
  roles:
    - { role: ansible-role-repo-epel, when: ansible_os_family == 'RedHat' }
    - ansible-role-docker
  tasks:
  - name: Fix FirewallD for RHEL8
    firewalld:
      zone: public
      masquerade: true
      permanent: true
      state: enabled
    when: ansible_distribution_major_version|int == 8
