# https://github.com/haxorof/ansible-role-docker-ce
- hosts: "{{selected_hosts}}"
  become: true
  roles:
    - ansible-role-repo-epel
    - ansible-role-pip
    - haxorof.docker_ce
  vars:
    selected_hosts: all
