# https://github.com/haxorof/ansible-role-docker-ce
- hosts: "{{selected_hosts}}"
  become: true
  roles:
    - haxorof.ansible-role-docker-ce
  tasks:
    - name: Fix FirewallD for RHEL8
      firewalld:
        zone: trusted
        interface: docker0
        permanent: yes
        state: enabled
      when: ansible_distribution_version|int == 8
