# https://github.com/haxorof/ansible-role-docker-ce
- hosts: "{{selected_hosts}}"
  become: true
  roles:
    - haxorof.ansible-role-docker-ce
  tasks:
    - name: Fix FirewallD for RHEL8
      firewalld:
        zone: public
        masquerade: true
        permanent: true
        state: enabled
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8
