# syntax=source.ansible
# https://prometheus-community.github.io/ansible/branch/main/node_exporter_role.html
---
- hosts: "{{ selected_hosts }}"
  become: true
  tasks:
    - name: Ensure node_exporter directory exist
      ansible.builtin.file:
        path: "{{ node_exporter_binary_install_dir | default('/usr/local/bin')  }}"
        state: directory
        mode: 0755
    - name: Install node_exporter
      ansible.builtin.include_role:
        name: prometheus.prometheus.node_exporter
