# syntax=source.ansible
# https://prometheus-community.github.io/ansible/branch/main/node_exporter_role.html
---
- hosts: "{{ selected_hosts }}"
  become: true
  roles:
    - prometheus.prometheus.node_exporter
