---
- hosts: "{{selected_hosts}}"
  become: true
  tasks:
    - name: Download rmate
      ansible.builtin.unarchive:
        src: https://github.com/listboss/rmate-rust/releases/download/v0.1.13/rmate_x86_64-unknown-linux-gnu.tar.gz target/x86_64-unknown-linux-gnu/release/rmate
        dest: /usr/local/bin/
        remote_src: yes
          - --transform
          - s/^rmate/atom/
