---
- hosts: "{{selected_hosts}}"
  become: true
  tasks:
    - name: Download rmate
      ansible.builtin.unarchive:
        src: https://github.com/spamwax/rmate-rs/releases/download/v1.0.3/rmate_x86_64-unknown-linux-gnu.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts:
          - --transform
          - s/target/x86_64-unknown-linux-gnu/release/rmateatom/
