---
- hosts: "{{ selected_hosts }}"
  become: true
  tasks:
    # Commented rust version
    # - name: Download rmate
    #   ansible.builtin.unarchive:
    #     src: https://github.com/spamwax/rmate-rs/releases/download/v1.0.3/rmate_x86_64-unknown-linux-gnu.tar.gz
    #     dest: /usr/local/bin/
    #     remote_src: true
    #     extra_opts:
    #       - --transform
    #       - s/^target\/x86_64-unknown-linux-gnu\/release\/rmate/atom/
    - name: Download rmate
      get_url:
        url: 'https://github.com/azhinu/rmate-rs/releases/download/v1.1.1/rmate-{{ ansible_architecture }}-unknown-linux-musl'
        dest: /usr/local/bin/atom
        mode: '0755'
