# https://github.com/githubixx/ansible-role-wireguard
---
- name: "Set up"
  hosts: {{selected_hosts}}
  become: true
  roles:
    - githubixx.ansible_role_wireguard
  vars:
    selected_hosts: all
    wireguard_remote_directory: "/etc/wireguard"
    wireguard_port: "51820"
    wireguard_interface: "wg0"
    wireguard_allowed_ips: "10.1.0.0/24"
  tasks:
    - sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
