#syntax=source.ansible
# https://github.com/githubixx/ansible-role-wireguard
---
- name: "Set up"
  hosts: "{{ selected_hosts }}"
  become: true
  roles:
    - ansible-role-wireguard
  vars:
    wireguard_remote_directory: "/etc/wireguard"
    wireguard_port: "51820"
    wireguard_interface: "wg0"
    wireguard_allowed_ips: "10.1.0.0/24"
  tasks:
    - name: Enable traffic forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
