#syntax=source.ansible
zsh_sheldon_tag: 0.8.5 #Sheldon version to download
zsh_users: [] #Users to apply ZSH dotfiles and shell
zsh_force_copy_dotfiles: false #If 'True' will override old ZSH dotfiles.
