---
- name: Add repo (Debian)
  apt:
    deb: "https://repo.zabbix.com/zabbix/5.2/{{ ansible_facts['distribution']|lower }}/pool/main/z/zabbix-release/zabbix-release_5.2-1+{{ ansible_facts['distribution_release']|lower }}_all.deb"
    update_cache: true
    state: present

- name: Install Zabbix agent
  package:
    name: zabbix-agent
    state: present

- name: Create config
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"

- name: Add Zabbix port to UFW
  community.general.ufw:
    rule: allow
    port: "{{ zabbix_client_port }}"
    proto: tcp
  when: add_firewall_rule | bool

- name: "Start Zabbix agent"
  service:
    name: zabbix-agent
    state: started
    enabled: yes
