---
- name: "Add repo (RedHat 7)"
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    state: present
  when: ansible_distribution_major_version == '7'
- name: "Add repo (RedHat 8)"
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
    state: present
  when: ansible_distribution_major_version == '8'

- name: Install Zabbix agent
  package:
    name: zabbix-agent
    state: present

- name: "Create config"
  template:
    src: zabbix_agentd.conf.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"

- name: "Include Asterisk monitoring"
  copy:
    src: asterisk.conf
    dest: /etc/zabbix/zabbix_agentd.d/asterisk.conf
  when: ansible_facts['os_family'] == "Sangoma"

- name: "Add zabbix to asterisk group"
  user:
    name: zabbix
    groups: asterisk
    append: yes
  when: ansible_facts['os_family'] == "Sangoma"

- name: "Add Zabbix port to Firewalld"
  firewalld:
    zone: public
    port: "{{ zabbix_client_port }}/tcp"
    state: enabled
    permanent: yes
  when: add_firewall_rule | bool

- name: Restart Firewalld
  service:
    name: zabbix-agent
    state: restarted
  when: add_firewall_rule | bool

- name: "Start Zabbix agent"
  service:
    name: zabbix-agent
    state: started
    enabled: yes
