#syntax=source.ansible
github_token: ""
upgrade: False

modern_unix_utils_list:
  - name: bat
    install: True
    alias: "cat='/usr/local/bin/bat -P'"
    github_repo: sharkdp/bat
    asset_name: x86_64-unknown-linux-musl
    is_archive: True
    extra_opts:
      - --strip=1
      - --no-anchored
      - bat

  - name: btm
    install: True
    alias: "top='/usr/local/bin/btm -b'"
    github_repo: ClementTsang/bottom
    asset_name: bottom_x86_64-unknown-linux-musl.tar.gz
    is_archive: True
    extra_opts:
      - --no-anchored
      - btm

  - name: ctop
    install: True
    github_repo: bcicen/ctop
    asset_name: linux-amd64
    is_archive: False

  - name: duf
    install: True
    alias: "df='/usr/local/bin/duf'"
    github_repo: muesli/duf
    asset_name: linux_x86_64.tar.gz
    is_archive: True
    extra_opts:
      - --no-anchored
      - duf

  - name: gdu
    install: True
    alias: "du='/usr/local/bin/gdu'"
    github_repo: dundee/gdu
    asset_name: gdu_linux_amd64
    is_archive: True
    extra_opts:
      - --transform
      - s/^gdu_linux_amd64/gdu/

  - name: procs
    install: true
    alias: "ps='/usr/local/bin/procs -p disable'"
    github_repo: dalance/procs
    asset_name: lnx
    is_archive: True


  - name: lsd
    install: True
    alias: "ls='/usr/local/bin/lsd --total-size -l'"
    github_repo: Peltoche/lsd
    asset_name: x86_64-unknown-linux-musl
    is_archive: True
    extra_opts:
      - --strip=1
      - --no-anchored
      - lsd
