#My Atom syntax selector
#syntax=source.ansible
---

- name: Update package cache
  package:
    update_cache: yes
  when: ansible_os_family != 'Darwin'

- name: Install zsh, git, wget
  package:
    name:
      - zsh
      - git
      - wget
      - fzf
    state: present
  #Brew don't work from root user on macOS
  when: not (ansible_user_id == 'root' and ansible_os_family == 'Darwin')

#Start sheldon block
#Which return rc 0 when command exists.
- name: Check Sheldon installed
  command: which sheldon
  changed_when: false
  failed_when: false
  check_mode: no
  register: command_not_exist

# Disable becouse of pip module is required on remote host.
# - name: Get latest Sheldon release
#   community.general.github_release:
#     user: rossmacarthur
#     repo: sheldon
#     action: latest_release
#   register: sheldon
#   when: command_not_exist.rc | bool

- name: Get Sheldon
  unarchive:
    src: "https://github.com/rossmacarthur/sheldon/releases/download/{{ sheldon_tag }}/sheldon-{{ sheldon_tag }}-x86_64-{{ 'apple-darwin' if ansible_os_family == 'Darwin' else 'unknown-linux-musl'}}.tar.gz"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
    creates: /usr/local/bin/sheldon
  when: command_not_exist.rc | bool
#End sheldon block

- name: Add user settings
  include_tasks: user_setup.yml
  when: users is defined
  loop: "{{ users }}"
  loop_control:
    loop_var: user
