#syntax=source.ansible
- name: "Copy dotfiles to homedir"
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: "/home/{{ user }}/{{ file | basename }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwX,g=rX,o=rX
    force: "{{ force_copy_dotfiles | bool }}"
  with_fileglob:
    - '.*'
  loop_control:
    loop_var: file

- name: "Copy sheldon config to homedir"
  ansible.builtin.copy:
    src: .sheldon
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwX,g=rX,o=rX
    force: "{{ force_copy_dotfiles | bool }}"

- name: "Template dotfiles to homedir"
  ansible.builtin.template:
    src: "{{ file }}"
    dest: /home/{{ user }}/{{ file | basename | regex_replace('\.j2$', '') }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_fileglob: 'templates/.*'
  loop_control:
    loop_var: file

- name: "Get ZSH path"
  ansible.builtin.shell: command -v zsh
  changed_when: false
  failed_when: false
  register: zsh_path

- name: Change default shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ zsh_path.stdout }}"
