#syntax=source.ansible
# - name: "Copy dotfiles to homedir"
#   copy:
#     src: "{{ file }}"
#     dest: "/home/{{ user }}/{{ file | basename }}"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: '644'
#     force: "{{ force_copy_dotfiles }}"
#   with_fileglob:
#     - '.*'
#   loop_control:
#     loop_var: file

# - name: "Create sheldon dir"
#   file:
#     path: /home/{{ user }}/.sheldon
#     state: directory
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: '0755'

- name: "Copy sheldon config to homedir"
  copy:
    src: /
    dest: "/home/{{ user }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    # mode: '0755'
    force: "{{ force_copy_dotfiles }}"
    directory_mode: true

- name: "Template dotfiles to homedir"
  ansible.builtin.template:
    src: "{{ file }}"
    dest: /home/{{ user }}/{{ file | basename |  regex_replace('\.j2$', '') }}
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_fileglob: 'templates/.*'
  loop_control:
    loop_var: file

- name: "Get ZSH path"
  command: command -v zsh
  changed_when: false
  failed_when: false
  register: zsh_path

- name: Change default shell
  user:
    name: "{{ user }}"
    shell: "{{ zsh_path.stdout_lines }}"
