- name: Delete root pw file /root/.pw (if present)
  file:
    path: /root/.pw
    state: absent

- name: install system updates for centos systems
  yum: name=* state=latest update_cache=yes
  when: ansible_distribution == "CentOS"

- name: Install required packages
  package:
    name: "{{ harden_linux_required_packages }}"
    state: latest
  retries: 2
  delay: 5
  ignore_errors: yes

- name: Install openntpd/ntp package if requested
  package:
    state: latest
    name: "{{ harden_linux_ntp }}"
  retries: 2
  delay: 5
  when: harden_linux_ntp is defined
  tags:
    - ntpd

- name: Set NTP config directory (depends on selected NTP package)
  set_fact:
    harden_linux_ntp_config_directory: '{% if harden_linux_ntp == "openntpd" %}openntpd/{% else %}{% endif %}'
  when: harden_linux_ntp is defined
  tags:
    - ntpd

- name: Add ntpd.conf if requested
  lineinfile:
    dest: "/etc/{{ harden_linux_ntp_config_directory }}ntpd.conf"
    regexp: "{{ item }}"
    line: "{{ harden_linux_ntp_settings[item] }}"
    state: "present"
  notify: "restart ntpd"
  when: harden_linux_ntp is defined
  with_items:
    - "{{ harden_linux_ntp_settings | list }}"
  tags:
    - ntpd

- name: Add deploy user
  user:
    name: awx
    password: yIS2fz06h2PK6
    uid: "{{ harden_linux_deploy_user_uid }}"
  tags:
    - user

- name: Add authorized keys for deploy user
  authorized_key:
    user: awx
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2wLt6UKHlRyHon2q8YG4Sbcxo/9wF17BVS1TzcCTn0woOZhHbnay5UZy4d/+P7j2kYS5vF0FlYvUXQ3EH31ykuz9fw5gIstBeC/Z+DCLbDBw1duaVl9lUe2a0C5Zhpe1c51RvYLydZYwErNu2vy2fkHcTjfTJAsWd64MKPZ2hP0Bh/mEVXAoEtws2LXIAY+egg9ZWm4yNhf9zYSPZW9slGmeqsdjf3WSK3WWEncumHNTUJNmfq04JOImt+VO+naeVUyTtxn7K4v/qtLjciIohkK1DD5RBywEDtxT81QZs1IgOznjs09DOHLDo2uHfxylc9wIPHK8qK/Tuwjd97ay3PrqckHW4zYjfgAMLxxXGZehm/pWrJMJKLneB+BFWrrpaZu/GDi0biJ9ZX1+OsDQ0Gir42tIvWKJUwEE9jGCYhvL7B17eD90AVqAGasRSrC+xN3qZrNgKX3KOpqSVR1DjItSz30yrjlh8UWWcb1/50nkoRfoE0HQhkaymXIQx6+E=
  tags:
    - user

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "awx ALL"
    line: "awx ALL=(ALL) NOPASSWD:ALL"
    state: present
  tags:
    - user
    - sudo

- name: Combine harden_linux_sshd_settings and harden_linux_sshd_settings_user (if defined)
  set_fact:
    harden_linux_sshd_settings: "{{ harden_linux_sshd_settings | combine(harden_linux_sshd_settings_user|default({})) }}"
  tags:
    - ssh

- name: Ensure sshd_config setting
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item }}"
    line: "{{ harden_linux_sshd_settings[item] }}"
    state: "present"
  notify: "restart ssh"
  with_items:
    - "{{ harden_linux_sshd_settings | list }}"
  tags:
    - ssh

- name: Combine harden_linux_sysctl_settings and harden_linux_sysctl_settings_user (if defined)
  set_fact:
    harden_linux_sysctl_settings: "{{ harden_linux_sysctl_settings | combine(harden_linux_sysctl_settings_user|default({})) }}"
  tags:
    - sysctl

- name: Sysctl settings
  sysctl:
    name: "{{ item }}"
    value: "{{ harden_linux_sysctl_settings[item] }}"
    sysctl_set: yes
  with_items:
    - "{{ harden_linux_sysctl_settings | list }}"
  tags:
    - sysctl

- name: Update Sshguard white list
  lineinfile:
    dest: /etc/sshguard.whitelist
    regexp: "^{{ item }}"
    line: "{{ item }}"
    state: present
  with_items:
    - "{{ harden_linux_sshguard_whitelist }}"
  tags:
    - sshguard
- name: Disable root user
  user:
    name: root
    password: "!"